name: Elixir CI

on:
  push:
    branches: [ main, staging ]
  pull_request:
    branches: [ main, staging ]

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Elixir
      uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
      with:
        elixir-version: '1.13.2' # Define the elixir version [required]
        otp-version: '24.1' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v2
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Run tests
      env: 
        LIST_DIR: "ls -la"
      run: |
        $LIST_DIR
        mix test
        
    - name: Check Staging
      if: ${{ github.ref_name == 'staging' }}
      run: echo "Yay! branch name is staging"
    - name: Check Main
      if: ${{ github.ref_name == 'main' }}
      run: echo "Yay! branch name is main"